# Generated by Django 5.2.16 on 2026-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('selected_voice', models.CharField(default='male', max_length=10)),
                ('custom_voice_b64', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
