# Generated by Django 5.2.16 on 2026-08-15 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userusage',
            name='is_tester',
            field=models.BooleanField(default=False),
        ),
    ]
